# This travis.yml was built to:
#   - install ruby
#   - run shell script
# We used the GitHub ruby client API to create the pull request
language: ruby
before_install:
  - 'git config --global user.email "algoliareadmebot@users.noreply.github.com"'
  - 'git config --global user.name "algoliareadmebot"'
  - rvm install 2.2.0
  - rvm use 2.2.0
  - gem install redcarpet -v 3.3.2
  - gem install octokit -v 4.3.0
script: tools/commit.sh
gemfile: Gemfile
branches:
  only:
    - master
env:
  global:
    # GH_TOKEN
    - secure: FrJgnOtz8OnY6hmCi0FpkMCoPJvmaCKxI11Y6TVtzV2S6bid+1rgCrKhmbR0psnRBniObErb0Wt/7/O1eVc3SP27mWrxuGXvmbxxu8q8F2TggZdHoJFzPl2k8bG7cpNnTCi22SkgSfNdcQq3WdMdbz90BSOVV1crz9xltALoOoU=